title: Rim Alhajal
logo: /assets/img/photo_rim.png
description: Dual master's graduate, currently looking for a role in the data science field.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
