title: Rim Hajal | PhD Student
author: Rim Hajal
email: rim.hajal@univ-grenoble-alpes.fr
description: > # this means to ignore newlines until "show_excerpts:"
  Personal academic website. Research updates,
  publications, and CV.
show_excerpts: true 
baseurl: ""

sass:
  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: Rim Hajal
  tagline: PhD Student · CNRS
  date_format: "%b %-d, %Y"
  style: black          
  showNav: true
  showPicker: false    

  navigation:
    - title: About
      url: "/about/"
    - title: Research
      url: "/research/"
    - title: Publications
      url: "/publications/"
    - title: CV
      url: "/cv/"
    - title: Contact
      url: "/contact/"

  social_links:
    github:  rimhajal
    linkedIn: in/rimhajal
    substack: rimhajal

  useMathJax: true


header_pages:
  - about.md
  - research.md
  - publications.md
  - cv.md
  - contact.md

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
